apiVersion: v1
kind: Namespace
metadata:
  name: step-install
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ca-files
  namespace: step-install
data:
  ca.config: |
    {
      "root_ca_name": "ACS INTERN AUTH",
      "intermediate_ca_name": "ACS INTERN DIST",
      "ca_org_name": "ACS INTERN CA ORG",
      "ca_orgunit_name": "ACS INTERN OU CA ORG",
      "ca_country_name": "DE",
      "ca_locality_name": "Aachen",
      "ca_dns_names": [
        "step-certificates.step-certificates.svc.cluster.local",
        "127.0.0.1"
      ],
      "jwk_provisioner_name": "admin",
      "ca_url": "step-certificates.step-certificates.svc.cluster.local"
    }
  root-tls.json.tpl: |
    {
      "subject": {
        "commonName": "${ROOT_CA_NAME}",
        "organization": "${CA_ORG_NAME}",
        "organizationalUnit": "${CA_ORGUNIT_NAME}",
        "country": "${CA_COUNTRY_NAME}",
        "locality": "${CA_LOCALITY_NAME}"
      },
      "keyUsage": [ "certSign", "crlSign" ],
      "basicConstraints": {
        "isCA": true,
        "maxPathLen": 1
      }
    }
  intermediate-tls.json.tpl: |
    {
      "subject": {
        "commonName": "${INTERMEDIATE_CA_NAME}",
        "organization": "${CA_ORG_NAME}",
        "organizationalUnit": "${CA_ORGUNIT_NAME}",
        "country": "${CA_COUNTRY_NAME}",
        "locality": "${CA_LOCALITY_NAME}"
      },
      "keyUsage": [ "certSign", "crlSign" ],
      "basicConstraints": {
        "isCA": true,
        "maxPathLen": 1
      }
    }
  values.yml.tpl: |
    kind: StatefulSet
    replicaCount: 1
    autocert:
      enabled: false
    bootstrap:
      enabled: false
    ca:
      db:
          enabled: true
          persistent: false
    inject:
      enabled: true
      config:
        files:
          ca.json:
            root: /home/step/certs/root_ca.crt
            federateRoots: []
            crt: /home/step/certs/intermediate_ca.crt
            key: /home/step/secrets/intermediate_ca_key
            address: 0.0.0.0:9000
            dnsNames: ${CA_DNS_NAMES}
            logger:
              format: json
            db:
              type: badgerv2
              dataSource: /home/step/db
            authority:
              claims:
                minTLSCertDuration: 5m
                maxTLSCertDuration: 24h
                defaultTLSCertDuration: 24h
                disableRenewal: false
                minHostSSHCertDuration: 5m
                maxHostSSHCertDuration: 1680h
                defaultHostSSHCertDuration: 720h
                minUserSSHCertDuration: 5m
                maxUserSSHCertDuration: 24h
                defaultUserSSHCertDuration: 24h
              provisioners:
                - type: ACME
                  name: acme
                  forceCN: true
                  claims: {}
                - type: SSHPOP
                  name: sshpop
                  claims:
                    enableSSHCA: true
                - type: JWK
                  name: ${JWK_PROVISIONER_NAME}
                  key: 
                    alg: "${JWK_PROVISIONER_CRT_ALG}"
                    crv: "${JWK_PROVISIONER_CRT_CRV}"
                    kid: "${JWK_PROVISIONER_CRT_KID}"
                    kty: "${JWK_PROVISIONER_CRT_KTY}"
                    use: "${JWK_PROVISIONER_CRT_USE}"
                    x: "${JWK_PROVISIONER_CRT_X}"
                    'y': "${JWK_PROVISIONER_CRT_Y}"
                  encryptedKey: "${JWK_PROVISIONER_KEY}"
                  claims:
                    enableSSHCA: true
            tls:
              cipherSuites:
                - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
                - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
                - TLS_AES_128_GCM_SHA256
              minVersion: 1.2
              maxVersion: 1.3
              renegotiation: false
          defaults.json:
            ca-url: ${CA_URL}
            ca-config: /home/step/config/ca.json
            fingerprint: ${TLS_ROOT_FINGERPRINT}
            root: /home/step/certs/root_ca.crt
        templates:
          x509_leaf.tpl: |
            {
              "subject": {{ toJson .Subject }},
              "sans": {{ toJson .SANs }},
            {{- if typeIs "*rsa.PublicKey" .Insecure.CR.PublicKey }}
              "keyUsage": ["keyEncipherment", "digitalSignature"],
            {{- else }}
              "keyUsage": ["digitalSignature"],
            {{- end }}
              "extKeyUsage": ["serverAuth", "clientAuth"]
            }
          ssh.tpl: |
            {
              "type": {{ toJson .Type }},
              "keyId": {{ toJson .KeyID }},
              "principals": {{ toJson .Principals }},
              "extensions": {{ toJson .Extensions }},
              "criticalOptions": {{ toJson .CriticalOptions }}
            }
      certificates:
        intermediate_ca: |
    ${TLS_INTERMEDIATE_CRT}
        root_ca: |
    ${TLS_ROOT_CRT}
        ssh_host_ca: "${SSH_HOST_CRT}"
        ssh_user_ca: "${SSH_USER_CRT}"
      secrets:
        ca_password: "${INTERMEDIATE_TLS_PASSWORD_B64}"
        provisioner_password: "${JWK_PROVISIONER_PASSWORD_B64}"
        certificate_issuer:
          enabled: false
        x509:
          enabled: true
          intermediate_ca_key: |
    ${TLS_INTERMEDIATE_KEY}
          root_ca_key: |
    ${TLS_ROOT_KEY}
        ssh:
          enabled: true
          host_ca_key: |
    ${SSH_HOST_KEY}
          host_ca_password: "${SSH_HOST_PASSWORD_B64}"
          user_ca_key: |
    ${SSH_USER_KEY}
          user_ca_password: "${SSH_USER_PASSWORD_B64}"
    service:
      type: ClusterIP
      port: 443
      targetPort: 9000
      nodePort: 32400
    ingress:
      enabled: false
      annotations: {}
      hosts: []
      tls: []


  generate-values.sh: |
    #!/bin/sh

    ROOT_CA_NAME=`jq -r '.root_ca_name' ca.config`
    INTERMEDIATE_CA_NAME=`jq -r '.intermediate_ca_name' ca.config`
    CA_ORG_NAME=`jq -r '.ca_org_name' ca.config`
    CA_ORGUNIT_NAME=`jq -r '.ca_orgunit_name' ca.config`
    CA_COUNTRY_NAME=`jq -r '.ca_country_name' ca.config`
    CA_LOCALITY_NAME=`jq -r '.ca_locality_name' ca.config`
    CA_DNS_NAMES=`jq -c .ca_dns_names ca.config`
    CA_URL=`jq -r .ca_url ca.config`
    JWK_PROVISIONER_NAME=`jq -r .jwk_provisioner_name ca.config`

    export ROOT_CA_NAME INTERMEDIATE_CA_NAME CA_ORG_NAME CA_ORGUNIT_NAME CA_COUNTRY_NAME CA_LOCALITY_NAME CA_DNS_NAMES CA_URL JWK_PROVISIONER_NAME

    # Write Out Root and Intermediate Certificate Templates
    cat root-tls.json.tpl | envsubst | tee root-tls.json
    cat intermediate-tls.json.tpl | envsubst | tee intermediate-tls.json

    # Generate Root and Intermediate Passwords
    ROOT_TLS_PASSWORD_B64=`tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_\`{|}~' </dev/urandom | head -c 64 | tee root-tls.password | base64 -w 0`
    INTERMEDIATE_TLS_PASSWORD_B64=`tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_\`{|}~' </dev/urandom | head -c 64 | tee intermediate-tls.password | base64 -w 0`

    # Generate Root CA Certificate Pair
    step certificate create \
      "${ROOT_CA_NAME}" \
      "root-tls.crt" \
      "root-tls.key" \
      --template="root-tls.json" \
      --kty="EC" \
      --curve="P-256" \
      --password-file="root-tls.password" \
      --not-before="0s" \
      --not-after="44520h" \
      --force

    TLS_ROOT_CRT=`cat root-tls.crt | sed 's/^/        /'`
    TLS_ROOT_KEY=`cat root-tls.key | sed 's/^/        /'`
    TLS_ROOT_FINGERPRINT=`step certificate fingerprint root-tls.crt`

    # Generate Intermediate CA Certificate Pair
    step certificate create \
      "${INTERMEDIATE_CA_NAME}" \
      "intermediate-tls.crt" \
      "intermediate-tls.key" \
      --template="intermediate-tls.json" \
      --kty="EC" \
      --curve="P-256" \
      --password-file="intermediate-tls.password" \
      --not-before="0s" \
      --not-after="17760h" \
      --ca="root-tls.crt" \
      --ca-key="root-tls.key" \
      --ca-password-file="root-tls.password" \
      --force

    TLS_INTERMEDIATE_CRT=`cat intermediate-tls.crt | sed 's/^/        /'`
    TLS_INTERMEDIATE_KEY=`cat intermediate-tls.key | sed 's/^/        /'`

    # Generate SSH Host CA Password
    SSH_HOST_PASSWORD=`tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_\`{|}~' </dev/urandom | head -c 64 | tee host-ssh.password`
    SSH_HOST_PASSWORD_B64=`echo ${SSH_HOST_PASSWORD} | base64 -w 0`

    # Generate SSH Host CA Keypair
    ssh-keygen -q -t ecdsa -b 256 -f host-ssh.key -C "SSH Host Key" -N ${SSH_HOST_PASSWORD}

    SSH_HOST_CRT=`cat host-ssh.key.pub`
    SSH_HOST_KEY=`cat host-ssh.key | sed 's/^/        /'`

    # Generate SSH User CA Password
    SSH_USER_PASSWORD=`tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_\`{|}~' </dev/urandom | head -c 64 | tee user-ssh.password`
    SSH_USER_PASSWORD_B64=`echo ${SSH_USER_PASSWORD} | base64 -w 0`

    # Generate SSH User CA Keypair
    ssh-keygen -q -t ecdsa -b 256 -f user-ssh.key -C "SSH User Key" -N ${SSH_USER_PASSWORD}

    SSH_USER_CRT=`cat user-ssh.key.pub`
    SSH_USER_KEY=`cat user-ssh.key | sed 's/^/        /'`

    JWK_PROVISIONER_PASSWORD_B64=`tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_\`{|}~' </dev/urandom | head -c 64 | tee jwk_provisioner.password | base64 -w 0`

    step crypto jwk create \
      jwk_provisioner.pub \
      jwk_provisioner.key \
      --kty=EC \
      --curve=P-256 \
      --use=sig \
      --password-file=jwk_provisioner.password \
      --force

    JWK_PROVISIONER_KEY=`cat jwk_provisioner.key | step crypto jose format | tee jwk_provisioner.compact.key`
    JWK_PROVISIONER_CRT_ALG=`jq '.alg' -r jwk_provisioner.pub`
    JWK_PROVISIONER_CRT_CRV=`jq '.crv' -r jwk_provisioner.pub`
    JWK_PROVISIONER_CRT_KID=`jq '.kid' -r jwk_provisioner.pub`
    JWK_PROVISIONER_CRT_KTY=`jq '.kty' -r jwk_provisioner.pub`
    JWK_PROVISIONER_CRT_USE=`jq '.use' -r jwk_provisioner.pub`
    JWK_PROVISIONER_CRT_X=`jq '.x' -r jwk_provisioner.pub`
    JWK_PROVISIONER_CRT_Y=`jq '.y' -r jwk_provisioner.pub`

    export \
      ROOT_TLS_PASSWORD_B64 TLS_ROOT_CRT TLS_ROOT_KEY TLS_ROOT_FINGERPRINT \
      INTERMEDIATE_TLS_PASSWORD_B64 TLS_INTERMEDIATE_CRT TLS_INTERMEDIATE_KEY \
      SSH_HOST_PASSWORD_B64 SSH_HOST_CRT SSH_HOST_KEY \
      SSH_USER_PASSWORD_B64 SSH_USER_CRT SSH_USER_KEY \
      JWK_PROVISIONER_PASSWORD_B64 JWK_PROVISIONER_KEY JWK_PROVISIONER_CRT_ALG \
      JWK_PROVISIONER_CRT_CRV JWK_PROVISIONER_CRT_KID JWK_PROVISIONER_CRT_KTY \
      JWK_PROVISIONER_CRT_USE JWK_PROVISIONER_CRT_X JWK_PROVISIONER_CRT_Y

    cat values.yml.tpl | envsubst | tee /res/values.yml > /dev/null

  
---
apiVersion: batch/v1
kind: Job
metadata:
  name: step-install
  namespace: step-install
spec:
  template:
    spec:
      securityContext:
        runAsUser: 0
      volumes:
        - name: ca-files-vol
          configMap:
            name: ca-files
        - name: shared-vol
          emptyDir: {}
        - name: results-vol
          hostPath:
            path: ${PARENT}/smallstep
            type: DirectoryOrCreate
      initContainers:
        - name: copy-files
          image: busybox
          command: ["sh", "-c", "cp /wd/* /shared/"]
          volumeMounts:
            - name: shared-vol
              mountPath: /shared
            - name: ca-files-vol
              mountPath: /wd
      containers:
      - name: generate-values
        image: cr.smallstep.com/smallstep/step-ca:0.29.0
        command: ["sh","-c","apk add envsubst && chmod -R 777 /shared/ && cd /shared && ./generate-values.sh"]
        volumeMounts:
          - name: shared-vol
            mountPath: /shared
          - name: results-vol
            mountPath: /res
      restartPolicy: Never
  backoffLimit: 1
